pipeline {

    agent any

    environment {

        REGISTRY      = "docker.io/avkhaladkar1991"
        IMAGE_NAME    = "payment-service"
        IMAGE_TAG     = "${BUILD_NUMBER}"
        DOCKER_IMAGE  = "${REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}"

        APP_REPO      = "https://github.com/avkhaladkar1991/argocd-payment-app.git"

    }

    options {
        timestamps()
    }

    stages {

        stage('Checkout Application Code') {

            steps {
                git branch: 'main',
                    credentialsId: 'github-creds',
                    url: "${APP_REPO}"
            }

        }

        stage('Build Docker Image') {

            steps {
                sh """
                docker build -t ${DOCKER_IMAGE} -f payment-service/Dockerfile payment-service
                """
            }

        }

        stage('Docker Login') {

            steps {

                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-creds',
                    usernameVariable: 'DOCKER_USER',
                    passwordVariable: 'DOCKER_PASS'
                )]) {

                    sh """
                    echo \$DOCKER_PASS | docker login -u \$DOCKER_USER --password-stdin
                    """

                }

            }

        }

        stage('Push Image') {

            steps {

                sh """
                docker push ${DOCKER_IMAGE}
                """

            }

        }

        stage('Cleanup') {

            steps {

                sh """
                docker rmi ${DOCKER_IMAGE} || true
                """

            }

        }

    }

    post {

        success {

            echo "✅ CI Pipeline Completed Successfully"
            echo "Image pushed: ${DOCKER_IMAGE}"

        }

        failure {

            echo "❌ CI Pipeline Failed"

        }

    }

}